# Generated by Django 2.2.6 on 2019-10-19 02:03

from django.db import migrations, models
import pomelo.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(upload_to=pomelo.generic.models.upload_to),
        ),
    ]
