# Generated by Django 2.2.6 on 2019-10-24 06:08

from django.db import migrations, models
import pomelo.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0002_auto_20191019_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(upload_to=pomelo.generic.models.upload_to)),
            ],
        ),
    ]
