# Generated by Django 2.2.6 on 2019-10-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authjwt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True, verbose_name='Phone'),
        ),
    ]
