# Generated by Django 2.2.6 on 2019-10-19 03:52

from django.db import migrations, models
import pomelo.authjwt.validators


class Migration(migrations.Migration):

    dependencies = [
        ('authjwt', '0002_auto_20191019_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='phone',
            field=models.CharField(default=None, max_length=20, null=True, unique=True, validators=[pomelo.authjwt.validators.UnicodePhoneValidator()], verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='username',
            field=models.CharField(default=None, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and _ only.', max_length=150, null=True, unique=True, validators=[pomelo.authjwt.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
