# Generated by Django 2.2.6 on 2019-12-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authjwt', '0004_auto_20191019_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='verify',
            field=models.CharField(default=None, max_length=6, null=True, verbose_name='验证码'),
        ),
    ]
