# Generated by Django 2.2.6 on 2020-01-21 02:55

from django.db import migrations, models
import pomelo.authjwt.validators


class Migration(migrations.Migration):

    dependencies = [
        ('authjwt', '0005_baseuser_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='username',
            field=models.CharField(default='nousername', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and _ only.', max_length=150, unique=True, validators=[pomelo.authjwt.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
    ]
